classes = [
    'banded',
    'blotchy',
    'braided',
    'bubbly',
    'bumpy',
    'chequered',
    'cobwebbed',
    'cracked',
    'crosshatched',
    'crystalline',
    'dotted',
    'fibrous',
    'flecked',
    'freckled',
    'frilly',
    'gauzy',
    'grid',
    'grooved',
    'honeycombed',
    'interlaced',
    'knitted',
    'lacelike',
    'lined',
    'marbled',
    'matted',
    'meshed',
    'paisley',
    'perforated',
    'pitted',
    'pleated',
    'polka-dotted',
    'porous',
    'potholed',
    'scaly',
    'smeared',
    'spiralled',
    'sprinkled',
    'stained',
    'stratified',
    'striped',
    'studded',
    'swirly',
    'veined',
    'waffled',
    'woven',
    'wrinkled',
    'zigzagged',
]

# each class has several possible class names, query for all of them via OR
class_map = dict()
for cls in classes:
    class_map[cls] = f'"{cls} texture" OR "{cls} pattern" OR "{cls} thing" OR "{cls} object"'

templates = [
    'a photo of a {} texture.',
    'a photo of a {} pattern.',
    'a photo of a {} thing.',
    'a photo of a {} object.',
    'a photo of the {} texture.',
    'a photo of the {} pattern.',
    'a photo of the {} thing.',
    'a photo of the {} object.',
]